### PR TITLE
Some Windows fixes

### PR DESCRIPTION
**Pull request by mastercoms**
Hi, pushed some fixes for Windows, mostly for mingw.

### CODE REVIEW

**Comment by selmf** [comment]
Thanks for the PR. I have no issue with adding the first two commits, but the third commit which attempts to fix the redefinition of __forceinline redefinition is a bit problematic.

I have not written the code segments with __forceinline myself, so I don't know about the profiling and performance tests involved that led to the decision to force inlining, but it is clear that the original code's intention is to define __forceinline to inline in contexts where __forceinline is not available.

The fix you're proposing thus has two issues:

1. It is too complicated and there is no explanation why it is needed
2. It tries to force __forceinline to inline in a context where it is not needed

To fix this, the best approach would probably to just use __forceinline as MinGW defines it. That should not take more than one or two lines of code :)

If you want to go the extra mile, you can also define __forceinline as "inline __attribute__((always_inline))" for GCC and compatible compilers, so we get the same behavior. Just don't forget to leave regular inline as fallback.

Last but not least, redefining __forceinline this way is probably an antipattern and I should consider to do some refactoring to avoid issues like this in the future.

**Comment by mastercoms** [comment]
Totally agree there, I just wasn't entirely sure what the intent was so tried to get the same behavior without redefining, which [caused a warning](https://github.com/gen2brain/go-unarr/runs/4805349127?check_suite_focus=true#step:4:8).

**Comment by mastercoms** [comment]
I'll remove the last commit and work on it in a new branch.

**Comment by selmf** [comment]
Not sure if a new branch is really needed. It should be enough to change the msvc check to a win32 check or add a mingw check since this behavior seems to be compiler specific. I will also look into adding a mingw toolchain to my CI so I can catch these issues in the future.

Am 26. Januar 2022 02:35:50 MEZ schrieb mastercoms ***@***.***>:

**Comment by mastercoms** [comment]
Are you interested in GitHub Actions CI?

**Comment by mastercoms** [comment]
> It should be enough to change the msvc check to a win32 check or add a mingw check since this behavior seems to be compiler specific.

The problem is that __forceinline has different sematics in mingw, due to being GCC based. It does not compile without overriding __forceinline for the file.

**Comment by mastercoms** [comment]
Refactored the force inline usage to use a custom define, and used the suggested attribute on non-MSVC.

**Comment by selmf** [comment]
Looks good :)

One more minor request: Could you change the macro name to UNARR_FORCE_INLINE? MY_FORCE_INLINE is already used by the third party code from 7z/LZMA sdk and I would like to keep the namespaces apart if possible.

Please also let me know how I should add you to the list of authors.

**Comment by mastercoms** [comment]
Done, and I'd prefer to use my username. My email is mastercoms@tuta.io.

**Pull request merged**
